/// Supabase backend configuration for the Showshop app.
///
/// The [supabaseAnonKey] is the *public* anonymous key generated by Supabase
/// and is safe to include in client-side code (it enforces Row Level Security
/// policies defined in the Supabase dashboard). Never store the *service role*
/// key in client code.
class SupabaseConfig {
  SupabaseConfig._();

  static const String supabaseUrl =
      'https://rdyszutpwabhqimvltvq.supabase.co';

  static const String supabaseAnonKey =
      'sb_publishable_zDg7dZ7TJVe0YTWdNTDg1w_9aurYp1M';

  /// Supabase Storage bucket that holds item images.
  static const String imageBucket = 'item-images';
}

